Update index.html
octocat/Spoon-Knife pull request #17131
Opened 2018-12-10 23:04 UTC by andrewpuleo

closes #17130

2018-12-22 13:25 UTC, ghost approved these changes

2018-12-25 00:23 UTC, alax99 requested changes
Looks bad!

2018-12-25 00:23 UTC, alax99 commented on index.html
> +  Innuendos are frowned upon, @octocat. Tsk tsk. *Responds with a hiss.*
Tsk Tsk?

2019-02-21 15:26 UTC, vasanthrt commented on index.html
> +  Innuendos are frowned upon, @octocat. Tsk tsk. *Responds with a hiss.*
what is tsk tsk ??

2019-02-21 15:31 UTC, 1337kid approved these changes

2019-02-21 15:31 UTC, 1337kid approved these changes

2021-01-08 00:00 UTC, closed without merging